version: '3.8'

services:

  mongodb:
    image: mongo:7.0
    container_name: mern-todo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern-todo-network

  server:
    build: ./server
    image: ${{DOCKERHUB_USERNAME}}/mern-server
    container_name: mern_todo_server
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongodb:27017/mern
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - mern-todo-network

  client:
    build: ./client
    image: ${{DOCKERHUB_USERNAME}}/mern-client
    container_name: mern-todo-client
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://server:8000
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - mern-todo-network

volumes:
  mongodb_data:
    driver: local

networks:
  mern-todo-network:
    driver: bridge
